### ISSUE TITLE
Wemo platform

### ISSUE THREAD

**Issue by crashflow** [cflurin/homebridge-mqtt#64]
I tried to get this to work with existing Wemo "outlets" but could not. The outlets were created using this plugin:
https://github.com/rudders/homebridge-platform-wemo
{
"platform": "BelkinWeMo",
"name": "WeMo Platform"
}

Even if you use the same name and service name it will create a new outlet in homebridge and homekit. 

Am I missing something?

Thanks

**Comment by cflurin** [comment]
Have a look here :https://github.com/cflurin/homebridge-mqtt/issues/8

**Comment by cflurin** [comment]
First you should understand how homebridge works.
https://github.com/nfarina/homebridge

**_"Homebridge is a lightweight NodeJS server you can run on your home network that emulates the iOS HomeKit API"_**

As the name sais homebridge is a bridge between HomeKit (iphone, ipad) and devices (sensors, switches, etc.). There are a lot of Plugins that you can install. One of them is homebridge-mqtt. With homebridge-mqtt you can add, remove, configure accessories at runtime. I like to use Node-red for all my stuff but you can also connect a device eg. using an ESP8266 or any system that has a MQTT API.

You don't need virtual devices but rather a tool on a Hardware like Raspberry Pi or ESP8266 to map data with the goal to use **non** HomeKit devices.

**Comment by lespatots** [comment]
Actually I have no problem interfacing various devices but what I really need is a simple interface between Node-Red and Homekit and there isn't one. So it seems the recommended workaround is using this plug-in and as far as I can tell the only way is creating virtual devices in Homekit and updating those from real devices or vice-versa.

**Comment by cflurin** [comment]
Still not clear what you mean by virtual device.
Some more infos would be helpful.
Please describe what you tried in node-red and in your HomeKit app (Home, EVE?).

As simple example such a Switch will do.

**Comment by lespatots** [comment]
I would like to generate a Node-red dashboard that shows the status of all my automated lights. Most lights are hue but some are not Homekit approved and some are driven by a Raspberry. There is no way to directly interface Homekit to Node-Red so I have choices. I could use Hue-Magic and read the light status or I could create a virtual light in Homekit which mirrors the status of a real lamp. That virtual light can update MQTT and thence Node-Red. In practice neither solution is good because of the large number of lamps. I could alternately add a virtual lamp to an Accessory Group and that would let me see the state of groups.

So a virtual device is an accessory created for the sole purpose of interfacing.

If I wanted to trigger a scene I could create a virtual switch which is set by MQTT and can be acted upon by Homekit to trigger the scene in Homekit.

Does that clarify? I don't really want to add/remove/configure devices at run time 'cos I don't see a use case? Is there one?

**Comment by cflurin** [comment]
As explained here :https://github.com/cflurin/homebridge-mqtt/issues/8 you can't access HomeKit accessories using homebridge-mqtt.

I also use philips hue lamps, they are connected with the hue bridge to HomeKit.
Additionally I use node-red-contrib-huemagic to control the lamps and for the node-red-dashboard.
As I said I use node-red for my home-automation and HomeKit as an additional "dashboard" and voice-control device.
Except philips hue lamps all my devices (zwave, enocean, xiaomi, netatmo, esp8266) are connected to node-red running on several Raspberry PI's. One the main Rpi is the mqtt-broker running.

"Runtime" means you can add, remove, configure etc. the accessories without the need to restart homebridge as often you have to do using other plugins.
